### ISSUE TITLE
Layout in every view folder

### ISSUE THREAD

**Issue by vadiraja** [btply/nodeshop#5]
Is there any specific reason as to why you have layout template in every view folder?

**Comment by matthewarkin** [comment]
Since you pointed this out I went and checked it out and set all the views to point to a layout.jade in the parent, which broke the checkout.

The checkout layouts don't include the categories, besides that the other layouts appear to be the same, though I'm a bit lazy to do a diff on them. 

Using some jade inheritance, you can have the base layout. Each folder than optionally includes the category nav in its layout, which inherits from the base. I ended up doing this and have a pull request in.

**Comment by btply** [comment]
Thanks for changing that matt, I was in the process of doing this for the admin side as well as getting rid of the data.js file which is fairly pointless
